### ISSUE TITLE
Simplify configuration file

### ISSUE THREAD

**Issue by gruyaume** [ellanetworks/core#157]
### Enhancement Proposal

We should simplify the project's configuration file

Proposed

```yaml
port: 1234
log-level: info
tls:
  cert: "testdata/cert.pem"
  key: "testdata/key.pem"
db:
  path: "testdata/sqlite.db"
interfaces:
  uplink: "eth0"
  radio: "eth1"
```

It's likely we modify this file as we learn more.
